sudo: required
services: 
    - docker

before_install:
    - docker build -t calebikhuohon/containerized-react -f Dockerfile.dev .

script:
    - docker run calebikhuohon/containerized-react npm run test -- --coverage